// Code generated by genx:code@v0.3.7 DO NOT EDIT.
package pipe

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[PIPE::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[PIPE::ERROR:0] undefined"
	case ERROR__PIPELINE_NOT_RUNNING:
		return "[PIPE::ERROR:1] PIPELINE_NOT_RUNNING"
	case ERROR__REACH_MAX_PENDING:
		return "[PIPE::ERROR:2] REACH_MAX_PENDING"
	case ERROR__PIPELINE_CANCELED:
		return "[PIPE::ERROR:3] PIPELINE_CANCELED"
	case ERROR__JOB_FAILED:
		return "[PIPE::ERROR:4] JOB_FAILED"
	case ERROR__JOB_CANCELED:
		return "[PIPE::ERROR:5] JOB_CANCELED"
	case ERROR__PIPELINE_JOB_PANICKED:
		return "[PIPE::ERROR:6] PIPELINE_JOB_PANICKED"
	case ERROR__PIPELINE_SUMMARY_PANICKED:
		return "[PIPE::ERROR:7] PIPELINE_SUMMARY_PANICKED"
	}
}
