package pipe

// Error defines error codes in pipe
// +genx:code
type Error uint8

const (
	ERROR_UNDEFINED Error = iota
	ERROR__PIPELINE_NOT_RUNNING
	ERROR__PIPELINE_CLOSED
	ERROR__REACH_MAX_PENDING
	ERROR__PIPELINE_CANCELED
	ERROR__PIPELINE_JOB_PANICKED
	ERROR__PIPELINE_SUMMARY_PANICKED
)
