// Code generated by genx:code@v0.3.7 DO NOT EDIT.
package nest

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[NEST::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[NEST::ERROR:0] undefined"
	case ERROR__NEST_CLOSED:
		return "[NEST::ERROR:1] NEST_CLOSED"
	case ERROR__NEST_CLOSE_TIMEOUT:
		return "[NEST::ERROR:2] NEST_CLOSE_TIMEOUT"
	}
}
