// Code generated by genx:code DO NOT EDIT.
package nest

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[nest.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[nest.Error:0] undefined"
	case ERROR__NEST_CLOSED:
		return "[nest.Error:1] NEST_CLOSED"
	case ERROR__NEST_CLOSE_TIMEOUT:
		return "[nest.Error:2] NEST_CLOSE_TIMEOUT"
	}
}
