// Code generated by genx:code@v0.3.7 DO NOT EDIT.
package schedx

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[SCHED:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[SCHED:0] undefined"
	case ERROR__REACH_MAX_PENDING:
		return "[SCHED:1] reached max pending limitation"
	case ERROR__SCHEDULER_NOT_RUNNING:
		return "[SCHED:2] Push before Run"
	case ERROR__SCHEDULER_RERUN:
		return "[SCHED:3] scheduler is already running"
	case ERROR__SCHEDULER_CANCELED:
		return "[SCHED:4] scheduler is canceled (Close or parent ctx)"
	case ERROR__SCHEDULER_JOB_PANICKED:
		return "[SCHED:5] scheduler job panicked"
	}
}
