// Code generated by genx:code@v0.3.7 DO NOT EDIT.
package schedx

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[SCHEDX::ERROR:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[SCHEDX::ERROR:0] undefined"
	case ERROR__REACH_MAX_PENDING:
		return "[SCHEDX::ERROR:1] reached max pending limitation"
	case ERROR__SCHEDULER_RERUN:
		return "[SCHEDX::ERROR:2] scheduler is already running"
	case ERROR__SCHEDULER_CANCELED:
		return "[SCHEDX::ERROR:3] scheduler is manual canceled"
	case ERROR__SCHEDULER_JOB_PANICKED:
		return "[SCHEDX::ERROR:4] scheduler job panicked"
	}
}
