// Code generated by genx:code DO NOT EDIT.
package schedx

import (
	"fmt"
)

func (e Error) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[schedx.Error:%d] unknown", e)
	case ERROR_UNDEFINED:
		return "[schedx.Error:0] undefined"
	case ERROR__REACH_MAX_PENDING:
		return "[schedx.Error:1] reached max pending limitation"
	case ERROR__SCHEDULER_RERUN:
		return "[schedx.Error:2] scheduler is already running"
	case ERROR__SCHEDULER_CANCELED:
		return "[schedx.Error:3] scheduler is manual canceled"
	case ERROR__SCHEDULER_JOB_PANICKED:
		return "[schedx.Error:4] scheduler job panicked"
	}
}
